version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes: 
      - jogo-emprestado-db:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports: 
      - 8081:8081
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    depends_on: 
      - mongo
    
  api-server:
    build: ./api
    restart: always
    ports: 
      - 5000:80
    environment: 
      MongoDB__Host: mongo
      UserApi: admin
      PasswordApi: admin123
      RoleApi: admin
    depends_on: 
      - mongo

  web-server:
    build:
      context: ./web
      dockerfile: Dockerfile
      args: 
        - REACT_APP_BACKEND_URL=http://localhost:5000/api/
    restart: always
    ports:
      - '8080:80'
    depends_on: 
      - api-server

volumes:
  jogo-emprestado-db:
    driver: local